using System.Collections.Generic;

namespace WarudoImporter.Serialized
{
    /// <summary>
    /// Unity's built-in type-tree string table. Type/name offsets with bit 31 set index
    /// into this table instead of the file's own string buffer.
    /// </summary>
    internal static class CommonStrings
    {
        internal static readonly Dictionary<uint, string> Table = new Dictionary<uint, string>
        {
            { 0u, "AABB" },
            { 5u, "AnimationClip" },
            { 19u, "AnimationCurve" },
            { 34u, "AnimationState" },
            { 49u, "Array" },
            { 55u, "Base" },
            { 60u, "BitField" },
            { 69u, "bitset" },
            { 76u, "bool" },
            { 81u, "char" },
            { 86u, "ColorRGBA" },
            { 96u, "Component" },
            { 106u, "data" },
            { 111u, "deque" },
            { 117u, "double" },
            { 124u, "dynamic_array" },
            { 138u, "FastPropertyName" },
            { 155u, "first" },
            { 161u, "float" },
            { 167u, "Font" },
            { 172u, "GameObject" },
            { 183u, "Generic Mono" },
            { 196u, "GradientNEW" },
            { 208u, "GUID" },
            { 213u, "GUIStyle" },
            { 222u, "int" },
            { 226u, "list" },
            { 231u, "long long" },
            { 241u, "map" },
            { 245u, "Matrix4x4f" },
            { 256u, "MdFour" },
            { 263u, "MonoBehaviour" },
            { 277u, "MonoScript" },
            { 288u, "m_ByteSize" },
            { 299u, "m_Curve" },
            { 307u, "m_EditorClassIdentifier" },
            { 331u, "m_EditorHideFlags" },
            { 349u, "m_Enabled" },
            { 359u, "m_ExtensionPtr" },
            { 374u, "m_GameObject" },
            { 387u, "m_Index" },
            { 395u, "m_IsArray" },
            { 405u, "m_IsStatic" },
            { 416u, "m_MetaFlag" },
            { 427u, "m_Name" },
            { 434u, "m_ObjectHideFlags" },
            { 452u, "m_PrefabInternal" },
            { 469u, "m_PrefabParentObject" },
            { 490u, "m_Script" },
            { 499u, "m_StaticEditorFlags" },
            { 519u, "m_Type" },
            { 526u, "m_Version" },
            { 536u, "Object" },
            { 543u, "pair" },
            { 548u, "PPtr<Component>" },
            { 564u, "PPtr<GameObject>" },
            { 581u, "PPtr<Material>" },
            { 596u, "PPtr<MonoBehaviour>" },
            { 616u, "PPtr<MonoScript>" },
            { 633u, "PPtr<Object>" },
            { 646u, "PPtr<Prefab>" },
            { 659u, "PPtr<Sprite>" },
            { 672u, "PPtr<TextAsset>" },
            { 688u, "PPtr<Texture>" },
            { 702u, "PPtr<Texture2D>" },
            { 718u, "PPtr<Transform>" },
            { 734u, "Prefab" },
            { 741u, "Quaternionf" },
            { 753u, "Rectf" },
            { 759u, "RectInt" },
            { 767u, "RectOffset" },
            { 778u, "second" },
            { 785u, "set" },
            { 789u, "short" },
            { 795u, "size" },
            { 800u, "SInt16" },
            { 807u, "SInt32" },
            { 814u, "SInt64" },
            { 821u, "SInt8" },
            { 827u, "staticvector" },
            { 840u, "string" },
            { 847u, "TextAsset" },
            { 857u, "TextMesh" },
            { 866u, "Texture" },
            { 874u, "Texture2D" },
            { 884u, "Transform" },
            { 894u, "TypelessData" },
            { 907u, "UInt16" },
            { 914u, "UInt32" },
            { 921u, "UInt64" },
            { 928u, "UInt8" },
            { 934u, "unsigned int" },
            { 947u, "unsigned long long" },
            { 966u, "unsigned short" },
            { 981u, "vector" },
            { 988u, "Vector2f" },
            { 997u, "Vector3f" },
            { 1006u, "Vector4f" },
            { 1015u, "m_ScriptingClassIdentifier" },
            { 1042u, "Gradient" },
            { 1051u, "Type*" },
            { 1057u, "int2_storage" },
            { 1070u, "int3_storage" },
            { 1083u, "BoundsInt" },
            { 1093u, "m_CorrespondingSourceObject" },
            { 1121u, "m_PrefabInstance" },
            { 1138u, "m_PrefabAsset" },
            { 1152u, "FileSize" },
            { 1161u, "Hash128" },
            { 1169u, "RenderingLayerMask" },
            { 1188u, "fixed_array" },
            { 1200u, "EntityId" },
            { 1209u, "LoadableObjectId" },
            { 1226u, "LoadableSceneId" },
        };
    }
}
